spring.application.name=springsecurity


#liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yml

#jpa
#postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/maner
spring.datasource.username=postgres
spring.datasource.password=suman
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect