spring.application.name=springsecurity
logging.level.root=info
logging.file.name=uman.log

#liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yml


#postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/maner
spring.datasource.username=postgres
spring.datasource.password=suman
spring.datasource.hikari.data-source-properties.ApplicationName=Suman


#jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8140


keycloak.url=http://localhost:8123/
keycloak.username=admin
keycloak.password=admin